-- MySQL Script generated by MySQL Workbench
-- Mon Apr 24 16:47:38 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema consultAlbum
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `consultAlbum` ;

-- -----------------------------------------------------
-- Schema consultAlbum
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `consultAlbum` DEFAULT CHARACTER SET utf8mb4 ;
USE `consultAlbum` ;

-- -----------------------------------------------------
-- Table `consultAlbum`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consultAlbum`.`table1` ;

CREATE TABLE IF NOT EXISTS `consultAlbum`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `consultAlbum`.`ca_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consultAlbum`.`ca_user` ;

CREATE TABLE IF NOT EXISTS `consultAlbum`.`ca_user` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `unique_key` VARCHAR(32) NOT NULL,
  `reg_date` DATETIME NOT NULL,
  `user_id` VARCHAR(32) NOT NULL,
  `token` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`unique_key`))
COMMENT = 'consulting_album_auth_table';

CREATE INDEX `INDEX` ON `consultAlbum`.`ca_user` (`idx` ASC);


-- -----------------------------------------------------
-- Table `consultAlbum`.`ca_album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consultAlbum`.`ca_album` ;

CREATE TABLE IF NOT EXISTS `consultAlbum`.`ca_album` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `unique_key` VARCHAR(32) NOT NULL,
  `reg_date` DATETIME NOT NULL,
  `title` VARCHAR(64) NOT NULL DEFAULT 'NULL',
  `user_key` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`unique_key`),
  CONSTRAINT `fk_album_user`
    FOREIGN KEY (`user_key`)
    REFERENCES `consultAlbum`.`ca_user` (`unique_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = 'album_gallery';

CREATE INDEX `INDEX` ON `consultAlbum`.`ca_album` (`idx` ASC);

CREATE INDEX `user_key` ON `consultAlbum`.`ca_album` (`user_key` ASC);


-- -----------------------------------------------------
-- Table `consultAlbum`.`ca_photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consultAlbum`.`ca_photo` ;

CREATE TABLE IF NOT EXISTS `consultAlbum`.`ca_photo` (
  `idx` INT NOT NULL AUTO_INCREMENT,
  `unique_key` VARCHAR(32) NOT NULL,
  `reg_date` DATETIME NOT NULL,
  `title` VARCHAR(64) NOT NULL,
  `recipe` VARCHAR(255) NULL DEFAULT NULL,
  `album_key` VARCHAR(32) NULL DEFAULT NULL,
  `comment` INT NULL DEFAULT NULL,
  `user_key` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`unique_key`),
  CONSTRAINT `fk_photo_album`
    FOREIGN KEY (`album_key`)
    REFERENCES `consultAlbum`.`ca_album` (`unique_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_photo_user`
    FOREIGN KEY (`user_key`)
    REFERENCES `consultAlbum`.`ca_user` (`unique_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = 'photos';

CREATE INDEX `INDEX` ON `consultAlbum`.`ca_photo` (`idx` ASC);

CREATE INDEX `album_key` ON `consultAlbum`.`ca_photo` (`album_key` ASC);

CREATE INDEX `user_key` ON `consultAlbum`.`ca_photo` (`user_key` ASC);


-- -----------------------------------------------------
-- Table `consultAlbum`.`ca_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `consultAlbum`.`ca_tags` ;

CREATE TABLE IF NOT EXISTS `consultAlbum`.`ca_tags` (
  `idx` INT NOT NULL DEFAULT NULL AUTO_INCREMENT,
  `photo_key` VARCHAR(32) NULL,
  `album_key` VARCHAR(32) NULL DEFAULT NULL,
  `title` VARCHAR(64) NOT NULL,
  `user_key` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idx`),
  CONSTRAINT `fk_tags_photo`
    FOREIGN KEY (`photo_key`)
    REFERENCES `consultAlbum`.`ca_photo` (`unique_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags_album`
    FOREIGN KEY (`album_key`)
    REFERENCES `consultAlbum`.`ca_album` (`unique_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags_user`
    FOREIGN KEY (`user_key`)
    REFERENCES `consultAlbum`.`ca_user` (`unique_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `photo_key` ON `consultAlbum`.`ca_tags` (`photo_key` ASC);

CREATE INDEX `album_key` ON `consultAlbum`.`ca_tags` (`album_key` ASC);

CREATE INDEX `user_key` ON `consultAlbum`.`ca_tags` (`user_key` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
